version: "3.9"

services:
  app1:
    build: .
    container_name: node1
    image: app
    ports: 
      - 8082:8082
    expose:
      - "8082"
    environment:
      - PORT_FIRST=8082
    networks:
      - node_network
  app2:
    build: .
    container_name: node2
    image: app
    ports: 
      - 8081:8081
    expose:
      - "8081"
    environment:
      - PORT_FIRST=8081
    networks:
      - node_network
  nginx:
    image: nginx:latest
    container_name: rev_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:3000
    networks:
      - node_network
    depends_on:
      - node1
      - node2

networks:
  node_network:
